### ISSUE TITLE
Bidcos-RF Fehler - Geräteeinstellungen nicht erreichbar

### ISSUE THREAD

**Issue by easyhoo** [leonsio/YAHM#80]
Hab jetzt mehrfach getestet, bekomme bei Aufruf der Geräteeinstellungen im CCU Webinterface folgende Fehlermeldung (unabhängig vom Gerät):

Das Gerät mit der Seriennummer 'LEQ1290135' vom Interface 'BidCos-RF' konnte nicht abgefragt werden! 

Aktuelle YAHM Version auf Ubuntu 16.04 (VM), aktuelle CCU2-Firmwareversion

**Comment by andreheuer** [comment]
Hallo,
auch bei mir tritt dieses Problem häufig auf. Mit einer vorherigen Version (bzw. LXCCU) hatte ich das Problem nie.
Zudem sind bei mir diese Geräte meistens auch unter "Servicemeldungen" als nicht erreichbar markiert. Normalerweise können aber auch nicht erreichbare Geräte konfiguriert werden.
Ich habe schon ein bisschen in diesem Thread hier gewühlt, aber bin nicht so recht schlau geworden:
http://homematic-forum.de/forum/viewtopic.php?f=18&t=31033&start=1730

Gleichzeitig habe ich unter openhab2 noch das Phänomen, dass sehr häufig folgende Meldung auftritt:
20:29:56.637 [INFO ] [ternal.communicator.HomematicGateway] - No event since 8057 seconds from gateway 'c19bb7a0', restarting RPC server
Hängt das womöglich zusammen?

**Comment by rzander** [comment]
Hatte seit dem letzten Update auch Probleme. Bei mir war/ist nach jedem Neustart die Datei /etc/config_templates/InterfacesList.xml leer... Wenn ich die Datei wie unter https://github.com/leonsio/YAHM/wiki/Problembehandlung#hs485-oder-hm-lan-gateway-zeigen-kein-status-an-ger%C3%A4te-einstellungen-seite-ist-leer beschrieben erstelle, funktioniert alles bis zum nächsten Neustart...  Prüf doch mal, ob die Datei InterfacesList.xml bei Dir gültig ist...

**Comment by easyhoo** [comment]
stimmt....bei mir auch leer.....nach Erstellung wie beschrieben klappt es nun auch bei mir (bus zum nächsten Neustart)
